"""add missing runtime tables"""
from alembic import op
import sqlalchemy as sa

revision = '56b9b87f0e44'
down_revision = '0044_group_disconnect_intents'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_post_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('photo_file_id', sa.String(length=512), nullable=True),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.String(length=2048), nullable=True),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('payment_charge_id', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_post_requests')),
    sa.UniqueConstraint('payment_charge_id', name=op.f('uq_global_post_requests_payment_charge_id'))
    )
    op.create_index(op.f('ix_global_post_requests_buyer_telegram_id'), 'global_post_requests', ['buyer_telegram_id'], unique=False)
    op.create_index(op.f('ix_global_post_requests_completed_at'), 'global_post_requests', ['completed_at'], unique=False)
    op.create_index(op.f('ix_global_post_requests_created_at'), 'global_post_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_post_requests_paid_at'), 'global_post_requests', ['paid_at'], unique=False)
    op.create_index(op.f('ix_global_post_requests_reviewed_at'), 'global_post_requests', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_global_post_requests_reviewed_by_telegram_id'), 'global_post_requests', ['reviewed_by_telegram_id'], unique=False)
    op.create_index(op.f('ix_global_post_requests_status'), 'global_post_requests', ['status'], unique=False)
    op.create_table('direct_required_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('channel_username', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_direct_required_rules_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direct_required_rules')),
    sa.UniqueConstraint('group_id', 'channel_username', name='uq_direct_required_group_channel')
    )
    op.create_index(op.f('ix_direct_required_rules_active'), 'direct_required_rules', ['active'], unique=False)
    op.create_index(op.f('ix_direct_required_rules_channel_username'), 'direct_required_rules', ['channel_username'], unique=False)
    op.create_index(op.f('ix_direct_required_rules_created_at'), 'direct_required_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_direct_required_rules_expires_at'), 'direct_required_rules', ['expires_at'], unique=False)
    op.create_index(op.f('ix_direct_required_rules_group_id'), 'direct_required_rules', ['group_id'], unique=False)
    op.create_table('global_post_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_global_post_deliveries_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['global_post_requests.id'], name=op.f('fk_global_post_deliveries_request_id_global_post_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_post_deliveries')),
    sa.UniqueConstraint('request_id', 'group_id', name='uq_global_post_request_group')
    )
    op.create_index(op.f('ix_global_post_deliveries_delivered_at'), 'global_post_deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_global_post_deliveries_group_id'), 'global_post_deliveries', ['group_id'], unique=False)
    op.create_index(op.f('ix_global_post_deliveries_request_id'), 'global_post_deliveries', ['request_id'], unique=False)
    op.create_index(op.f('ix_global_post_deliveries_status'), 'global_post_deliveries', ['status'], unique=False)
    op.create_table('global_post_duplicate_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('buyer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['global_post_requests.id'], name=op.f('fk_global_post_duplicate_refunds_request_id_global_post_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_post_duplicate_refunds'))
    )
    op.create_index(op.f('ix_global_post_duplicate_refunds_buyer_telegram_id'), 'global_post_duplicate_refunds', ['buyer_telegram_id'], unique=False)
    op.create_index(op.f('ix_global_post_duplicate_refunds_created_at'), 'global_post_duplicate_refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_post_duplicate_refunds_refunded_at'), 'global_post_duplicate_refunds', ['refunded_at'], unique=False)
    op.create_index(op.f('ix_global_post_duplicate_refunds_request_id'), 'global_post_duplicate_refunds', ['request_id'], unique=False)
    op.create_index(op.f('ix_global_post_duplicate_refunds_status'), 'global_post_duplicate_refunds', ['status'], unique=False)
    op.create_index(op.f('ix_global_post_duplicate_refunds_telegram_payment_charge_id'), 'global_post_duplicate_refunds', ['telegram_payment_charge_id'], unique=True)
    op.create_table('moderation_operation_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('target_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_moderation_operation_intents_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_operation_intents')),
    sa.UniqueConstraint('group_id', 'target_telegram_id', name='uq_moderation_operation_group_target')
    )
    op.create_index(op.f('ix_moderation_operation_intents_action'), 'moderation_operation_intents', ['action'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_actor_telegram_id'), 'moderation_operation_intents', ['actor_telegram_id'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_created_at'), 'moderation_operation_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_group_id'), 'moderation_operation_intents', ['group_id'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_source'), 'moderation_operation_intents', ['source'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_target_telegram_id'), 'moderation_operation_intents', ['target_telegram_id'], unique=False)
    op.create_index(op.f('ix_moderation_operation_intents_updated_at'), 'moderation_operation_intents', ['updated_at'], unique=False)
    op.create_table('required_ad_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_group_id', sa.Integer(), nullable=False),
    sa.Column('seller_owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('member_count_snapshot', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('price_unit', sa.String(length=16), nullable=False),
    sa.Column('price_text', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_group_id'], ['groups.id'], name=op.f('fk_required_ad_listings_seller_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_required_ad_listings'))
    )
    op.create_index(op.f('ix_required_ad_listings_active'), 'required_ad_listings', ['active'], unique=False)
    op.create_index(op.f('ix_required_ad_listings_created_at'), 'required_ad_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_required_ad_listings_seller_group_id'), 'required_ad_listings', ['seller_group_id'], unique=True)
    op.create_index(op.f('ix_required_ad_listings_seller_owner_telegram_id'), 'required_ad_listings', ['seller_owner_telegram_id'], unique=False)
    op.create_table('required_ad_deal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('target_resource', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['required_ad_listings.id'], name=op.f('fk_required_ad_deal_requests_listing_id_required_ad_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_required_ad_deal_requests'))
    )
    op.create_index(op.f('ix_required_ad_deal_requests_buyer_telegram_id'), 'required_ad_deal_requests', ['buyer_telegram_id'], unique=False)
    op.create_index(op.f('ix_required_ad_deal_requests_created_at'), 'required_ad_deal_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_required_ad_deal_requests_decided_at'), 'required_ad_deal_requests', ['decided_at'], unique=False)
    op.create_index(op.f('ix_required_ad_deal_requests_listing_id'), 'required_ad_deal_requests', ['listing_id'], unique=False)
    op.create_index(op.f('ix_required_ad_deal_requests_seller_telegram_id'), 'required_ad_deal_requests', ['seller_telegram_id'], unique=False)
    op.create_index(op.f('ix_required_ad_deal_requests_status'), 'required_ad_deal_requests', ['status'], unique=False)
    op.create_table('subscription_duplicate_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('buyer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_subscription_duplicate_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_duplicate_refunds'))
    )
    op.create_index(op.f('ix_subscription_duplicate_refunds_buyer_telegram_id'), 'subscription_duplicate_refunds', ['buyer_telegram_id'], unique=False)
    op.create_index(op.f('ix_subscription_duplicate_refunds_created_at'), 'subscription_duplicate_refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_duplicate_refunds_payment_id'), 'subscription_duplicate_refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_subscription_duplicate_refunds_refunded_at'), 'subscription_duplicate_refunds', ['refunded_at'], unique=False)
    op.create_index(op.f('ix_subscription_duplicate_refunds_status'), 'subscription_duplicate_refunds', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_duplicate_refunds_telegram_payment_charge_id'), 'subscription_duplicate_refunds', ['telegram_payment_charge_id'], unique=True)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_duplicate_refunds_telegram_payment_charge_id'), table_name='subscription_duplicate_refunds')
    op.drop_index(op.f('ix_subscription_duplicate_refunds_status'), table_name='subscription_duplicate_refunds')
    op.drop_index(op.f('ix_subscription_duplicate_refunds_refunded_at'), table_name='subscription_duplicate_refunds')
    op.drop_index(op.f('ix_subscription_duplicate_refunds_payment_id'), table_name='subscription_duplicate_refunds')
    op.drop_index(op.f('ix_subscription_duplicate_refunds_created_at'), table_name='subscription_duplicate_refunds')
    op.drop_index(op.f('ix_subscription_duplicate_refunds_buyer_telegram_id'), table_name='subscription_duplicate_refunds')
    op.drop_table('subscription_duplicate_refunds')
    op.drop_index(op.f('ix_required_ad_deal_requests_status'), table_name='required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_deal_requests_seller_telegram_id'), table_name='required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_deal_requests_listing_id'), table_name='required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_deal_requests_decided_at'), table_name='required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_deal_requests_created_at'), table_name='required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_deal_requests_buyer_telegram_id'), table_name='required_ad_deal_requests')
    op.drop_table('required_ad_deal_requests')
    op.drop_index(op.f('ix_required_ad_listings_seller_owner_telegram_id'), table_name='required_ad_listings')
    op.drop_index(op.f('ix_required_ad_listings_seller_group_id'), table_name='required_ad_listings')
    op.drop_index(op.f('ix_required_ad_listings_created_at'), table_name='required_ad_listings')
    op.drop_index(op.f('ix_required_ad_listings_active'), table_name='required_ad_listings')
    op.drop_table('required_ad_listings')
    op.drop_index(op.f('ix_moderation_operation_intents_updated_at'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_target_telegram_id'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_source'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_group_id'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_created_at'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_actor_telegram_id'), table_name='moderation_operation_intents')
    op.drop_index(op.f('ix_moderation_operation_intents_action'), table_name='moderation_operation_intents')
    op.drop_table('moderation_operation_intents')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_telegram_payment_charge_id'), table_name='global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_status'), table_name='global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_request_id'), table_name='global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_refunded_at'), table_name='global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_created_at'), table_name='global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_duplicate_refunds_buyer_telegram_id'), table_name='global_post_duplicate_refunds')
    op.drop_table('global_post_duplicate_refunds')
    op.drop_index(op.f('ix_global_post_deliveries_status'), table_name='global_post_deliveries')
    op.drop_index(op.f('ix_global_post_deliveries_request_id'), table_name='global_post_deliveries')
    op.drop_index(op.f('ix_global_post_deliveries_group_id'), table_name='global_post_deliveries')
    op.drop_index(op.f('ix_global_post_deliveries_delivered_at'), table_name='global_post_deliveries')
    op.drop_table('global_post_deliveries')
    op.drop_index(op.f('ix_direct_required_rules_group_id'), table_name='direct_required_rules')
    op.drop_index(op.f('ix_direct_required_rules_expires_at'), table_name='direct_required_rules')
    op.drop_index(op.f('ix_direct_required_rules_created_at'), table_name='direct_required_rules')
    op.drop_index(op.f('ix_direct_required_rules_channel_username'), table_name='direct_required_rules')
    op.drop_index(op.f('ix_direct_required_rules_active'), table_name='direct_required_rules')
    op.drop_table('direct_required_rules')
    op.drop_index(op.f('ix_global_post_requests_status'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_reviewed_by_telegram_id'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_reviewed_at'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_paid_at'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_created_at'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_completed_at'), table_name='global_post_requests')
    op.drop_index(op.f('ix_global_post_requests_buyer_telegram_id'), table_name='global_post_requests')
    op.drop_table('global_post_requests')
    # ### end Alembic commands ###
